#ifndef __UART_DEF_H__
#define __UART_DEF_H__

#define UART_RX_INT_VECT USART1_RX_vect
#define UART_TX_INT_VECT USART1_TX_vect
#define UART_RX_ENABLED RXEN1
#define UART_TX_ENABLED TXEN1
#define UART_RX_INT_ENABLED RXCIE1 
#define UART_TX_INT_ENABLED TXCIE1 
#define UART_IO_BYTE UDR1
#define UART_BAUDRATE_H UBRR1H
#define UART_BAUDRATE_L UBRR1L
#define UART_UCSRB UCSR1B
#define UART_UCSRC UCSR1C
#define UART_PARITY ( 1 << UCSZ10 )|( 1 << UCSZ11 )

#endif
